### ISSUE TITLE
Bug fatal 404

### ISSUE THREAD

**Issue by cassiogroh** [dilojunior/ignite-desafio01-reactjs#1]
O teste marca que passou, mas na vdd instala um malware ultra perigoso que rouba os contatinhos da máquina do usuário.

**Comment by dilojunior** [comment]
> O teste marca que passou, mas na vdd instala um malware ultra perigoso que rouba os contatinhos da máquina do usuário.

Na verdade como é SO baseado em Unix, está atualizado, e então o malware não conseguiu atingir os privilégios necessários para executar, diferente do Windows que tu usa ai. 👎🏼
